### ISSUE TITLE
please provide release archive

### ISSUE THREAD

**Issue by EricDeveaud** [danny-wilson/omegaMap#2]
Hello, 

would you provide a release archive. 
it will ease the packager work.

regards

Eric

**Comment by danny-wilson** [comment]
Can you explain in more detail what you are requesting.

**Comment by EricDeveaud** [comment]
provide a tarball of the current git hub repository with a version number.

see https://help.github.com/en/articles/creating-releases 

thanks

Eric

**Comment by danny-wilson** [comment]
Thanks. I believe that's done now.

best wishes,
Danny

**Comment by EricDeveaud** [comment]
thanks

Eric
